name: Debugger Firmware CI

on:
  push:
    branches: [ main ]
    paths: 
    - '.github/workflows/build_firmware.yml'
    - 'firmware/**'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/build_firmware.yml'
    - 'firmware/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache toolchain
      id: cache
      uses: actions/cache@v1
      with: 
        path: /opt/riscv64-unknown-elf
        key : ${{runner.OS}}-riscv64-unknown-elf-caches-${{ hashFiles('bin/riscv64-unknown-elf-gcc') }}

    - name: Download toolchain
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        wget -c https://dev.bouffalolab.com/media/upload/download/riscv64-elf-x86_64-20210120.tar.gz
        mkdir /opt/riscv64-unknown-elf
        tar -zxvf riscv64-elf-x86_64-20210120.tar.gz -C /opt/riscv64-unknown-elf
    - name: Make firmware
      run: |
        git submodule init
        git submodule update
        cd firmware/bl_mcu_sdk
        PATH="/opt/riscv64-unknown-elf/bin:$PATH"
        make BOARD=bl702_debugger APP_DIR=../app APP=usb2uartjtag
        make BOARD=bl702_debugger_dualuart APP_DIR=../app APP=usb2dualuart
    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: sipeed_rv_debuger_plus_firmware
        path: |
          firmware/bl_mcu_sdk/out/app/usb2uartjtag/*
          firmware/bl_mcu_sdk/out/app/usb2dualuart/*